# fly.toml file generated for navidrome on 2022-09-24T18:12:08-04:00
app = "navidrome"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
ND_BASEURL = ""
ND_DATAFOLDER = "/data"
ND_LOGLEVEL = "info"
ND_MUSICFOLDER = "/music"
ND_SCANSCHEDULE = "1h"
ND_SESSIONTIMEOUT = "24h"

[experimental]
allowed_public_ports = []
auto_rollback = true

[mounts]
destination = "/data"
source = "navidrome_data"

[[services]]
http_checks = []
internal_port = 4533
processes = ["app"]
protocol = "tcp"
script_checks = []

[services.concurrency]
hard_limit = 25
soft_limit = 20
type = "connections"
# No open ports or checks. Available on tailnet only.
