# fly.toml file generated for radio-012a on 2022-09-24T19:39:51-04:00
app = "radio-012a"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
AZURACAST_DC_REVISION = "14"
STATION_NAME = "rpg_music"

[experimental]
allowed_public_ports = []
auto_rollback = true

[mounts]
destination = "/var/lib/mysql"
source = "data"

[[services]]
internal_port = 80
protocol = "tcp"

[services.concurrency]
hard_limit = 25
soft_limit = 20
type = "connections"

[[services.ports]]
force_https = true
handlers = ["http"]
port = 80

[[services.ports]]
handlers = ["tls", "http"]
port = 443

# Have to open the icecast port up publicly since tailscale's dns is being
# overwritten in resolv.conf
[[services]]
internal_port = 8005
protocol = "tcp"

[[services.ports]]
port = 8005
