# fly.toml file generated for radio-012a on 2022-09-24T19:39:51-04:00
app = "radio-012a"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
AZURACAST_DC_REVISION = 14
STATION_NAME = "rpg_music"

[experimental]
allowed_public_ports = []
auto_rollback = true

# Unfortunately, we can't change azuracast storage directories, so we mount all of var.
[mounts]
destination = "/var/lib/mysql"
source = "data"

[[services]]
internal_port = 80
protocol = "tcp"

[services.concurrency]
hard_limit = 25
soft_limit = 20
type = "connections"

[[services.ports]]
force_https = true
handlers = ["http"]
port = 80

[[services.ports]]
handlers = ["tls", "http"]
port = 443

[[services.tcp_checks]]
grace_period = "1s"
interval = "15s"
restart_limit = 0
timeout = "2s"
